utils: fix leak for map unpacking
fluent/ctraces pull request #40
Opened 2023-07-28 11:28 UTC by DavidKorczynski

This is an attempt to fix a leak in `ctr_mpack_unpack_map`. I don't think the fix is the generally best solution but would prefer if some maintainers adjust for the right leak.

The problem is that  the loop:  https://github.com/fluent/ctraces/blob/b0ac0de67f80f9f3a1e3f3c80e7ba03e4b1864e9/src/ctr_mpack_utils.c#L367-L397

can dynamically allocate memory on the line https://github.com/fluent/ctraces/blob/b0ac0de67f80f9f3a1e3f3c80e7ba03e4b1864e9/src/ctr_mpack_utils.c#L378

which is not always freed later.

To my analysis, the central problem is if some iterations in the loop allocate memory and then the final iteration of the loop sets the value of `result` to `CTR_MPACK_ERROR`, then the memory allocations from the loop iterations will not be freed later. This is because the dynamically allocated memory attached to `context` which is typecasted in the callees but is never casted back in case of needing to clean up.

Example stack trace of the leak:

```bash
==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 23 byte(s) in 1 object(s) allocated from:
    #0 0x52ef96 in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x57b698 in sds_alloc /src/fluent-bit/lib/cfl/src/cfl_sds.c:47:11
    #2 0x57b698 in cfl_sds_create_size /src/fluent-bit/lib/cfl/src/cfl_sds.c:164:12
    #3 0x5796d7 in ctr_mpack_consume_string_tag /src/fluent-bit/lib/ctraces/src/ctr_mpack_utils.c:244:22
    #4 0x5793be in ctr_mpack_consume_string_or_nil_tag /src/fluent-bit/lib/ctraces/src/ctr_mpack_utils.c:29:18
    #5 0x5751a7 in unpack_span_trace_state /src/fluent-bit/lib/ctraces/src/ctr_decode_msgpack.c:437:12
    #6 0x57a73c in ctr_mpack_unpack_map /src/fluent-bit/lib/ctraces/src/ctr_mpack_utils.c:378:30
    #7 0x574b05 in unpack_span /src/fluent-bit/lib/ctraces/src/ctr_decode_msgpack.c:569:12
    #8 0x57a9bb in ctr_mpack_unpack_array /src/fluent-bit/lib/ctraces/src/ctr_mpack_utils.c:444:18
    #9 0x574626 in unpack_scope_span_spans /src/fluent-bit/lib/ctraces/src/ctr_decode_msgpack.c:576:12
    #10 0x57a73c in ctr_mpack_unpack_map /src/fluent-bit/lib/ctraces/src/ctr_mpack_utils.c:378:30
    #11 0x57439a in unpack_scope_span /src/fluent-bit/lib/ctraces/src/ctr_decode_msgpack.c:609:12
    #12 0x57a9bb in ctr_mpack_unpack_array /src/fluent-bit/lib/ctraces/src/ctr_mpack_utils.c:444:18
    #13 0x572b46 in unpack_resource_span_scope_spans /src/fluent-bit/lib/ctraces/src/ctr_decode_msgpack.c:616:12
    #14 0x57a73c in ctr_mpack_unpack_map /src/fluent-bit/lib/ctraces/src/ctr_mpack_utils.c:378:30
    #15 0x57286b in unpack_resource_span /src/fluent-bit/lib/ctraces/src/ctr_decode_msgpack.c:651:12
    #16 0x57a9bb in ctr_mpack_unpack_array /src/fluent-bit/lib/ctraces/src/ctr_mpack_utils.c:444:18
    #17 0x572706 in unpack_resource_spans /src/fluent-bit/lib/ctraces/src/ctr_decode_msgpack.c:658:12
    #18 0x57a73c in ctr_mpack_unpack_map /src/fluent-bit/lib/ctraces/src/ctr_mpack_utils.c:378:30
    #19 0x5724f7 in unpack_context /src/fluent-bit/lib/ctraces/src/ctr_decode_msgpack.c:669:12
    #20 0x5724f7 in ctr_decode_msgpack_create /src/fluent-bit/lib/ctraces/src/ctr_decode_msgpack.c:691:14
    #21 0x569f05 in LLVMFuzzerTestOneInput /src/fluent-bit/tests/internal/fuzzers/ctrace_fuzzer.c:16:5
    #22 0x43de03 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #23 0x429562 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #24 0x42ee0c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #25 0x458342 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #26 0x7fd13413e082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
```

2023-07-28 13:47 UTC, DavidKorczynski commented
> I don't think the fix is the generally best solution but would prefer if some maintainers adjust for the right leak.

Specifically, it's not a general solution because the leaks happens other values set similarly across `ctr_decode_msgpack` and the key issue seems ot be `ctr_mpack_unpack_map` fails to clean up in situations where some decoding is successful and some is unsuccessful

2023-08-08 18:07 UTC, leonardo-albertovich requested changes
Please move the definition of `context_to_free` to the beginning of the function and reneame it as `context_to_release` if possible while at it.

2023-08-08 18:39 UTC, leonardo-albertovich commented
Actually, I'm sorry David, even though the style request was technically correct, I didn't pay attention to what the change actually was.

I think the change is wrong because the conditional branch you put that cleanup in is something that should be handled by the caller.

What happens when the map key handler returns anything but `CTR_MPACK_SUCCESS` is that error should be elevated and each scope should perform the necessary cleanup for things that aren't handled by an outer function.

From what I can see the issue in this case is that in [line 569](https://github.com/fluent/ctraces/blob/d503d2867a346e82d203eebe7d3021bdf508af13/src/ctr_decode_msgpack.c#L569) we shouldn't return the result of the `ctr_mpack_unpack_map` call but instead save it in a local variable and if it's not `CTR_MPACK_SUCCESS` we should use `ctr_span_destroy` to dispose of `context->span` and set it to `NULL`.

Please correct me if I'm wrong or let me know if you have any questions.

2023-08-08 21:53 UTC, DavidKorczynski commented
I tried this Leonardo, but it didn't work and in general I don't think it's possible to have the fix there.

The problem is that the leak happens in a loop where the loop itself doesn't have knowledge of the underlying element, which in this case has the consequence it cannot free all data associated with the element. This is what I meant from the initial PR text *This is because the dynamically allocated memory attached to context which is typecasted in the callees but is never casted back in case of needing to clean up.*. 

I think in essence there is missing information available when unpacking map/arrays and this makes it tricky to clean it up. The problem is if parts of the elements in the map/arrays are succesfully unpacked but the unpacking later fails, then it seems like leaks happen. I think this extends further than spans as well.

2023-08-09 08:22 UTC, leonardo-albertovich commented
Could you please share the patch you applied so I can assist you with it? It's probably something simple because I'm fairly sure that it can be addressed in this way.

2023-09-28 17:59 UTC, leonardo-albertovich approved these changes

2023-09-28 18:01 UTC, leonardo-albertovich commented
@edsiper this PR should be merged ASAP. 

Should @DavidKorczynski increase the patch level in this PR or will we do it afterwards?

2023-09-28 18:32 UTC, merged

2023-09-28 18:32 UTC, edsiper commented
@leonardo-albertovich pls bump it, thank you